# Generated by Django 4.1.1 on 2022-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nasdaq", "0002_alter_mosttraded_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="mosttraded", name="id",),
        migrations.AlterField(
            model_name="mosttraded",
            name="index",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mosttraded",
            name="symbol",
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name="mosttraded", name="volume", field=models.FloatField(),
        ),
    ]
