# Generated by Django 4.1.1 on 2022-09-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nasdaq", "0003_remove_mosttraded_id_alter_mosttraded_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="mosttraded", options={"managed": True},),
    ]
